### ISSUE TITLE
You should do the same thing, but with YouTube

### ISSUE THREAD

**Issue by AkitaAttribute** [Incipiens/GoogleDriveReplacementBot#1]
Use Python to convert zip files into video files, and upload them privately.  Since YouTube doesn't limit your storage space, just the size of the files.

**Comment by Incipiens** [comment]
> Use Python to convert zip files into video files, and upload them privately. Since YouTube doesn't limit your storage space, just the size of the files.

Hahaha stay tuned to XDA later today, I did exactly that 😉
